### ISSUE TITLE
unable to display partial bond

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [mhchem/mhchemParser#1]
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/54144759/194407038-1f415c18-33d5-4cae-9574-197afd4c3ce7.png">

Cortex is using mhchemParser where it is unable to display chemical bonds. It throws an error saying to report. Was wondering if you could help out with this.

Thanks!

**Comment by mhchem** [comment]
Thanks for reporting. This is an issue with MathLive, which modifies the `~` to a space _before_ handing to to mhchemParser.
Referring to https://github.com/arnog/mathlive/issues/1647
